name: Send email on push

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v2.5.0
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Email Notification: New changes pushed to the repository"
          to: h266094@gmail.com
          from: h266094@outlook.com
          body: |
            Changes have been pushed to the repository, please review.
